import { PARTY } from "../../data/balance.js";
import { earn } from "../money.js";
import { param } from "../parameters.js";
import { botDifficulty, successChance, ticksBetween } from "./bots.js";
import type { Match } from "../../match/Match.js";
import type { PlayerState } from "../../match/playerState.js";
import type {
  PartyAction,
  PartyActionResult,
  PartyGame,
  PartySession,
  PartySetup,
} from "./types.js";

/**
 * Escape the maze.
 *
 * Fifteen seconds to drag from the box in the top-right corner to the exit. Timed
 * rather than blocking: it ends for the whole table at once, so nobody is left
 * staring at a maze while the match moves on without them.
 *
 * ⚠️ GENERATED BY CARVING, NOT BY GUESSING. The obvious way to build a random
 * maze is to punch random holes in a wall grid and then check whether it can be
 * solved — which fails often, and "generate until one works" is an unbounded
 * loop inside a game tick. A randomised depth-first carve is solvable BY
 * CONSTRUCTION: it walks the grid knocking down walls between cells it has not
 * visited yet, so every cell is reachable from every other one the moment it
 * finishes. There is no failure case to retry.
 *
 * The result is a "perfect" maze — exactly one route between any two cells,
 * with no loops. That is the right flavour here: five seconds is not long
 * enough to explore alternatives, so a maze with shortcuts would mostly be
 * deciding winners by luck.
 */

/** Walls are held per cell, one bit each, so the client can draw them directly. */
export interface MazeCell {
  /** True when there is a wall on that side of this cell. */
  top: boolean;
  right: boolean;
  bottom: boolean;
  left: boolean;
}

export interface MazeLayout {
  size: number;
  /** Row-major, `size * size` cells. */
  cells: MazeCell[];
  /** Where the draggable box starts (top-right, as specified). */
  start: { row: number; col: number };
  /** Where it has to get to. */
  exit: { row: number; col: number };
}

const OPPOSITE = { top: "bottom", bottom: "top", left: "right", right: "left" } as const;
type Side = keyof typeof OPPOSITE;

/**
 * Carves a perfect maze with an iterative randomised depth-first search.
 *
 * Iterative rather than recursive on purpose: a 10×10 grid is only 100 cells,
 * but this runs inside the tick loop and a stack that grows with the grid is a
 * cliff waiting for whoever raises the size.
 */
export function generateMaze(size: number, rng: () => number): MazeLayout {
  const cells: MazeCell[] = Array.from({ length: size * size }, () => ({
    top: true,
    right: true,
    bottom: true,
    left: true,
  }));
  const at = (row: number, col: number) => row * size + col;
  const visited = new Set<number>();

  // Start the carve where the player starts, so the first few cells — the ones
  // they see immediately — are always part of a long corridor rather than a
  // dead end pressed against the corner.
  const startRow = 0;
  const startCol = size - 1;
  const stack: number[] = [at(startRow, startCol)];
  visited.add(stack[0]!);

  while (stack.length > 0) {
    const current = stack[stack.length - 1]!;
    const row = Math.floor(current / size);
    const col = current % size;

    const neighbours: { side: Side; index: number }[] = [];
    if (row > 0 && !visited.has(at(row - 1, col)))
      neighbours.push({ side: "top", index: at(row - 1, col) });
    if (row < size - 1 && !visited.has(at(row + 1, col)))
      neighbours.push({ side: "bottom", index: at(row + 1, col) });
    if (col > 0 && !visited.has(at(row, col - 1)))
      neighbours.push({ side: "left", index: at(row, col - 1) });
    if (col < size - 1 && !visited.has(at(row, col + 1)))
      neighbours.push({ side: "right", index: at(row, col + 1) });

    if (neighbours.length === 0) {
      stack.pop();
      continue;
    }

    const pick = neighbours[Math.min(neighbours.length - 1, Math.floor(rng() * neighbours.length))]!;
    // Knock the wall down on BOTH sides. A wall recorded on one cell only is
    // the classic maze bug: it draws correctly and blocks movement in one
    // direction, so the route looks open and refuses to be walked.
    cells[current]![pick.side] = false;
    cells[pick.index]![OPPOSITE[pick.side]] = false;
    visited.add(pick.index);
    stack.push(pick.index);
  }

  return {
    size,
    cells,
    start: { row: startRow, col: startCol },
    exit: { row: size - 1, col: 0 },
  };
}

/** Whether a route is legal: adjacent steps, no wall between them, ends at the exit. */
export function routeIsLegal(maze: MazeLayout, route: { row: number; col: number }[]): boolean {
  if (route.length === 0) return false;
  const first = route[0]!;
  const last = route[route.length - 1]!;
  if (first.row !== maze.start.row || first.col !== maze.start.col) return false;
  if (last.row !== maze.exit.row || last.col !== maze.exit.col) return false;

  for (let i = 1; i < route.length; i++) {
    const from = route[i - 1]!;
    const to = route[i]!;
    if (
      to.row < 0 ||
      to.col < 0 ||
      to.row >= maze.size ||
      to.col >= maze.size ||
      from.row < 0 ||
      from.col < 0 ||
      from.row >= maze.size ||
      from.col >= maze.size
    ) {
      return false;
    }
    const dRow = to.row - from.row;
    const dCol = to.col - from.col;
    // One orthogonal step at a time. Diagonals would let a client cut corners
    // through walls, which is exactly the move a cheat would make.
    if (Math.abs(dRow) + Math.abs(dCol) !== 1) return false;

    const cell = maze.cells[from.row * maze.size + from.col]!;
    if (dRow === -1 && cell.top) return false;
    if (dRow === 1 && cell.bottom) return false;
    if (dCol === -1 && cell.left) return false;
    if (dCol === 1 && cell.right) return false;
  }
  return true;
}

export const MAZE_GAME: PartyGame = {
  id: "maze",
  description: "Escape the maze",
  timedSeconds: PARTY.MAZE_SECONDS,
  maxSeconds: PARTY.MAZE_SECONDS + 2,
  // Five seconds costs everybody the same five seconds of production whether
  // they play or not, so there is nothing to stop.
  stopsProduction: false,

  setup(match, players) {
    // ONE maze for the whole table. Everybody solving a different one would
    // make the reward a comment on which maze you drew rather than how fast you
    // moved.
    const maze = generateMaze(
      param("party.mazeSize", PARTY.MAZE_SIZE),
      match.rng,
    );
    const perPlayer: PartySetup["perPlayer"] = {};
    for (const player of players) perPlayer[player.id] = {};
    return { shared: { maze: maze as unknown as Record<string, unknown> }, perPlayer };
  },

  act(match, session, player, action): PartyActionResult {
    if (action.type !== "solve") return { ok: false, error: "Unknown action" };
    const me = session.players[player.id];
    if (!me || me.done) return { ok: false, error: "Already finished" };

    const maze = session.shared.maze as unknown as MazeLayout;
    const route = Array.isArray(action.route)
      ? (action.route as { row: number; col: number }[])
      : [];

    // ⚠️ THE ROUTE IS REPLAYED, NOT BELIEVED. A client that could report "I made
    // it" would win this every time by sending that and nothing else. It sends
    // the path it dragged; the walls it claims to have passed through are
    // checked here.
    if (!routeIsLegal(maze, route)) {
      return { ok: false, error: "That route does not walk the maze" };
    }

    me.done = true;
    me.outcome = "won";
    me.finishedTick = match.tick;
    earn(player, param("party.mazeReward", PARTY.MAZE_REWARD));
    return { ok: true };
  },

  tick() {
    // Nothing per-tick: the session's own clock ends a timed game.
  },

  bot(match, session, player) {
    const me = session.players[player.id];
    if (!me || me.done) return;
    // A bot "drags" for a plausible moment and then either makes it or does
    // not. The moment is rolled once, so a bot never finishes on the same frame
    // as everybody else; whether it gets out is its difficulty's business.
    if (me.data.botFinishTick === undefined) {
      me.data.botFinishTick = session.startedTick + ticksBetween(match.rng, 1.5, 4.5);
      return;
    }
    if (match.tick < (me.data.botFinishTick as number)) return;

    me.done = true;
    const solved = match.rng() < successChance(botDifficulty(match, player.id));
    me.outcome = solved ? "won" : "lost";
    me.finishedTick = match.tick;
    if (solved) earn(player, param("party.mazeReward", PARTY.MAZE_REWARD));
  },

  result() {
    return null; // "none"
  },
};

/** Exported for the debug launcher and tests. */
export function mazeOf(session: PartySession): MazeLayout {
  return session.shared.maze as unknown as MazeLayout;
}
